### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Tyr Chen",
    "email": "tchen@acme.org",
    "password": "123456"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}

### signin user (valid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### signin user (invalid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}


### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}
